# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='hl_key',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='hl_queue',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='hl_service',
        ),
        migrations.AddField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpline.Service'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
