# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0051_auto_20180522_1118'),
        ('helpline', '0002_auto_20180808_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='hl_abused',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_acategory',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_anotes',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_caseworker',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_counsellor',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_creator',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_culprit',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_details',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_escalateto',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_hiv',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_justice',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_notes',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_priority',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_registry',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_status',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_subcategory',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_subsubcat',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_supervisor',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_type',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_unique',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_victim',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_victimassessment',
        ),
        migrations.RemoveField(
            model_name='case',
            name='hl_victimkey',
        ),
        migrations.RemoveField(
            model_name='case',
            name='isrefferedfrom',
        ),
        migrations.AddField(
            model_name='case',
            name='instance',
            field=models.ManyToManyField(to='logger.Instance'),
        ),
    ]
