# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0003_auto_20180817_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Report', to='helpline.Case'),
        ),
    ]
