# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0004_auto_20180824_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='hl_unique',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
