# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0005_case_hl_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='hl_unique',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
