# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0006_report_hl_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hl_unique',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Unique Call-ID'),
        ),
    ]
