# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpline', '0008_auto_20180825_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock',
            name='hl_key',
        ),
        migrations.AddField(
            model_name='clock',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
