# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0051_auto_20180522_1118'),
        ('helpline', '0009_auto_20180825_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='call_xform',
            field=models.ForeignKey(blank=True, help_text='Call Case Form', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_xform', to='logger.XForm'),
        ),
        migrations.AddField(
            model_name='service',
            name='qa_xform',
            field=models.ForeignKey(blank=True, help_text='Quality Analysis Form', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_xform', to='logger.XForm'),
        ),
        migrations.AddField(
            model_name='service',
            name='walkin_xform',
            field=models.ForeignKey(blank=True, help_text='Walkin Case Form', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walkin_xform', to='logger.XForm'),
        ),
        migrations.AddField(
            model_name='service',
            name='web_online_xform',
            field=models.ForeignKey(blank=True, help_text='Quality Analysis Form', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_online_xform', to='logger.XForm'),
        ),
    ]
