# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0013_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='priority',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
